/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.csculminating.gui;

import java.awt.BorderLayout;

/**
 *
 * @author CaGid4274
 */
public class GraphPage extends javax.swing.JFrame {
public boolean isOpen = true;
    /**
     * Creates new form GraphPage
     */
    public GraphPage() {
        initComponents();
        double[][][] dataSet = {
//    {
//        // Line 1: Steep exponential curve
//        {0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100},
//        {1, 10, 100, 300, 600, 1000, 1500, 2100, 2800, 3600, 4500}
//    },
//    {
//        // Line 2: Horizontal line at large y (tests horizontal drawing & top Y limit)
//        {0, 50, 100, 150, 200, 250, 300},
//        {4000, 4000, 4000, 4000, 4000, 4000, 4000}
//    },
//    {
//        // Line 3: Sharp drop (tests vertical resolution and line break smoothness)
//        {0, 10, 20, 30, 40, 50},
//        {2000, 1500, 1000, 500, 10, -1000}
//    },
//    {
//        // Line 4: Negative curve (tests bottom quadrant and axis flipping)
//        {0, 10, 20, 30, 40, 50, 60},
//        {0, -10, -30, -60, -100, -150, -210}
//    },
//    {
//        // Line 5: Flat line near zero (precision check)
//        {0, 50, 100, 150, 200, 250, 300},
//        {0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1}
//    },
    {
        // Line 6: Zig-zag/jagged pattern (tests rendering of rapid direction change)
        {0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50},
        {0, 100, -100, 100, -100, 100, -100, 100, -100, 100, -100}
    }
};
        GraphPanel intro = new GraphPanel(dataSet, tempGraph);
        tempGraph.add(intro, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        tempGraph = new javax.swing.JPanel();
        TitleScreen1 = new javax.swing.JLabel();
        CloseButtonBorder = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setBackground(new java.awt.Color(204, 204, 204));
        closeButton.setText("Close");
        closeButton.setBorder(null);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 610, 580, 30));

        tempGraph.setBackground(new java.awt.Color(204, 204, 204));
        tempGraph.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout tempGraphLayout = new javax.swing.GroupLayout(tempGraph);
        tempGraph.setLayout(tempGraphLayout);
        tempGraphLayout.setHorizontalGroup(
            tempGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        tempGraphLayout.setVerticalGroup(
            tempGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        getContentPane().add(tempGraph, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 600, 300));

        TitleScreen1.setBackground(new java.awt.Color(153, 153, 153));
        TitleScreen1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 96)); // NOI18N
        TitleScreen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleScreen1.setText("Collision Graph ");
        TitleScreen1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(TitleScreen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 600, -1));

        CloseButtonBorder.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(CloseButtonBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 608, 584, 34));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        
        GUI.changeOpenG();
        setVisible(false);
        
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CloseButtonBorder;
    private javax.swing.JLabel TitleScreen1;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel tempGraph;
    // End of variables declaration//GEN-END:variables
}
