/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.csculminating.gui;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.lang.model.SourceVersion;
import javax.swing.JFileChooser;

/**
 *
 * @author CaGid4274
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public static boolean isOpen = false;
    public GUI() {
        initComponents();
        
    }

    public static void changeOpen()
    {
        isOpen = !isOpen;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SimButton = new javax.swing.JButton();
        GraphButton = new javax.swing.JButton();
        DataButton = new javax.swing.JButton();
        InputButton = new javax.swing.JButton();
        TitleScreen1 = new javax.swing.JLabel();
        TitleScreen2 = new javax.swing.JLabel();
        AnimPlaceHolder = new javax.swing.JPanel();
        temp = new javax.swing.JLabel();
        SimButtonBorder = new javax.swing.JPanel();
        GraphButtonBorder = new javax.swing.JPanel();
        DataButtonBorder = new javax.swing.JPanel();
        InputButtonBorder = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(620, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SimButton.setBackground(new java.awt.Color(204, 204, 204));
        SimButton.setText("Simulation");
        SimButton.setBorder(null);
        SimButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SimButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 500, 180, 40));

        GraphButton.setBackground(new java.awt.Color(204, 204, 204));
        GraphButton.setText("Graph");
        GraphButton.setBorder(null);
        GraphButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GraphButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 500, 180, 40));

        DataButton.setBackground(new java.awt.Color(204, 204, 204));
        DataButton.setText("Data");
        DataButton.setBorder(null);
        DataButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(DataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 500, 180, 40));

        InputButton.setBackground(new java.awt.Color(204, 204, 204));
        InputButton.setText("Select a File");
        InputButton.setBorder(null);
        InputButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputButtonActionPerformed(evt);
            }
        });
        getContentPane().add(InputButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 580, 580, 30));

        TitleScreen1.setBackground(new java.awt.Color(153, 153, 153));
        TitleScreen1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 96)); // NOI18N
        TitleScreen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleScreen1.setText("1D Collision");
        TitleScreen1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(TitleScreen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 410, -1));

        TitleScreen2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 96)); // NOI18N
        TitleScreen2.setText("Simulator");
        getContentPane().add(TitleScreen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        AnimPlaceHolder.setBackground(new java.awt.Color(204, 204, 204));

        temp.setText("Insert Animation Here");
        AnimPlaceHolder.add(temp);

        getContentPane().add(AnimPlaceHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 300, 140));

        SimButtonBorder.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(SimButtonBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 498, 184, 44));

        GraphButtonBorder.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(GraphButtonBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 498, 184, 44));

        DataButtonBorder.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(DataButtonBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 498, 184, 44));

        InputButtonBorder.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(InputButtonBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 578, 584, 34));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SimButtonActionPerformed

    private void GraphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphButtonActionPerformed
      
        GraphPage open = new GraphPage();
        if(!isOpen)
        {
            open.setVisible(true);
            isOpen = !isOpen;
        }
        
        
        
    }//GEN-LAST:event_GraphButtonActionPerformed

    private void InputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputButtonActionPerformed
        
        JFileChooser fileChooser = new JFileChooser();
        
        int response = fileChooser.showOpenDialog(null); //select the file to open
        
        if (response ==JFileChooser.APPROVE_OPTION)
        {
            
            File file = new File(fileChooser.getSelectedFile().getAbsolutePath());
            
            String csvFile = fileChooser.getSelectedFile().getAbsolutePath();
            BufferedReader reader = null;
            String line = "";
            
            try{
                reader = new BufferedReader(new FileReader(csvFile));
                while((line = reader.readLine())!= null){
                    
                    String[] row = line.split(",");
                    
                    for(String index : row)
                    {
                     
                        System.out.printf("%-10s", index);
                    }
                    System.out.println();
                }    
            }
            catch(Exception e){
            e.printStackTrace();
            }
            finally{
                try {
                      reader.close();
                    } 
                    catch (Exception e) {
                    e.printStackTrace();
                    }   
                }
            
            
            
            
        }
    }//GEN-LAST:event_InputButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AnimPlaceHolder;
    private javax.swing.JButton DataButton;
    private javax.swing.JPanel DataButtonBorder;
    private javax.swing.JButton GraphButton;
    private javax.swing.JPanel GraphButtonBorder;
    private javax.swing.JButton InputButton;
    private javax.swing.JPanel InputButtonBorder;
    private javax.swing.JButton SimButton;
    private javax.swing.JPanel SimButtonBorder;
    private javax.swing.JLabel TitleScreen1;
    private javax.swing.JLabel TitleScreen2;
    private javax.swing.JLabel temp;
    // End of variables declaration//GEN-END:variables
}
