/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.csculminating.gui;

import java.awt.BorderLayout;

/**
 *
 * @author caden
 */
public class SimPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SimPage.class.getName());

    
    
    /**
     * Creates new form SimPage
     */
    private ImportFile data;
    private SimulationPanel simPanel;
    /**
     * Creates new form SimPage
     */
    public SimPage(ImportFile importFile) {
        initComponents();
        this.data = importFile; // Store it
        
        SimSpeedSlider.setMaximum(500);
        SimSpeedSlider.setMinimum(75);
        SimSpeedSlider.setValue(325);
        double[][] simData = importFile.graphData; // access the 2D array
        
        Cart cart1 = new Cart(1, -1, 150);
        Cart cart2 = new Cart(1, 1, 60);
        
        SimulationPanel idea = new SimulationPanel(simData, "pe", false, cart1, cart2, tempSim);
        this.simPanel = idea;
        tempSim.add(idea, BorderLayout.CENTER);
        idea.startSimulation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        CloseButtonBorder = new javax.swing.JPanel();
        TitleScreen1 = new javax.swing.JLabel();
        tempSim = new javax.swing.JPanel();
        loopButton = new javax.swing.JButton();
        loopButtonBorder = new javax.swing.JPanel();
        pauseButton = new javax.swing.JButton();
        pauseButtonBorder = new javax.swing.JPanel();
        SimSpeedSlider = new javax.swing.JSlider();
        SliderLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(620, 700));
        setMinimumSize(new java.awt.Dimension(620, 700));
        setPreferredSize(new java.awt.Dimension(620, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setBackground(new java.awt.Color(204, 204, 204));
        closeButton.setText("Close");
        closeButton.setBorder(null);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 610, 580, 30));

        CloseButtonBorder.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(CloseButtonBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 608, 584, 34));

        TitleScreen1.setBackground(new java.awt.Color(153, 153, 153));
        TitleScreen1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 96)); // NOI18N
        TitleScreen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleScreen1.setText("Simulation");
        TitleScreen1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(TitleScreen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 600, -1));

        tempSim.setBackground(new java.awt.Color(204, 204, 204));
        tempSim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout tempSimLayout = new javax.swing.GroupLayout(tempSim);
        tempSim.setLayout(tempSimLayout);
        tempSimLayout.setHorizontalGroup(
            tempSimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );
        tempSimLayout.setVerticalGroup(
            tempSimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        getContentPane().add(tempSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 230, 580, 300));

        loopButton.setBackground(new java.awt.Color(204, 204, 204));
        loopButton.setText("Reset");
        loopButton.setBorder(null);
        loopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loopButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loopButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 570, 280, 30));

        loopButtonBorder.setBackground(new java.awt.Color(153, 153, 153));
        loopButtonBorder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(loopButtonBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 568, 284, 34));

        pauseButton.setBackground(new java.awt.Color(204, 204, 204));
        pauseButton.setText("Pause");
        pauseButton.setBorder(null);
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pauseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 570, 280, 30));

        pauseButtonBorder.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(pauseButtonBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 568, 284, 34));

        SimSpeedSlider.setMajorTickSpacing(1);
        SimSpeedSlider.setMinimum(10);
        SimSpeedSlider.setMinorTickSpacing(1);
        SimSpeedSlider.setValue(250);
        getContentPane().add(SimSpeedSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 190, 580, -1));

        SliderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SliderLabel.setText("Simulation Speed (Reset to Apply)");
        getContentPane().add(SliderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 170, 580, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed

        GUI.changeOpenS();
        setVisible(false);

    }//GEN-LAST:event_closeButtonActionPerformed

    private void loopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loopButtonActionPerformed
        // TODO add your handling code here:
        simPanel.resetFrameIndex(SimSpeedSlider.getValue());
    }//GEN-LAST:event_loopButtonActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        // TODO add your handling code here:
        simPanel.pauseFrameIndex();
    }//GEN-LAST:event_pauseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(() -> new SimPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CloseButtonBorder;
    private javax.swing.JSlider SimSpeedSlider;
    private javax.swing.JLabel SliderLabel;
    private javax.swing.JLabel TitleScreen1;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton loopButton;
    private javax.swing.JPanel loopButtonBorder;
    private javax.swing.JButton pauseButton;
    private javax.swing.JPanel pauseButtonBorder;
    private javax.swing.JPanel tempSim;
    // End of variables declaration//GEN-END:variables

}
